# Generated by Django 3.2.3 on 2021-05-17 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('Kategorie_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nazwa', models.CharField(max_length=50)),
                ('Opis', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('Kategorie_id',),
            },
        ),
        migrations.CreateModel(
            name='Dania',
            fields=[
                ('Danie_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Cena', models.IntegerField()),
                ('Kategorie_id', models.IntegerField()),
                ('Opis', models.CharField(max_length=100)),
                ('Danie_Kategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restauracja_app.kategorie')),
            ],
            options={
                'ordering': ('Danie_id',),
            },
        ),
    ]
